---
title: "tugas_prak_1"
output: html_document
---

# Import Library & Load Data

```{r}
library(readxl)
library(dplyr)
library(forecast)
library(graphics)
library(TTR)
library(TSA)
library(rio)
library(ggplot2)
```

```{r}
data <- read_excel("D:/IPB/Semester 5/MPDW/mpdw/Data praktikum/Rafif.xlsx")
head(data)
```

```{r}
df <- data %>%
  mutate(
    Tanggal = as.Date(Tanggal, format = "%b %d, %Y"),
    Harga = as.numeric(gsub(",", "", Harga))
  )

print(df)
```

```{r}
df <- df[order(df$Tanggal), ]
df
```


```{r}
View(df)
str(df)
dim(df)
```

```{r}
df.ts <- ts(df$Harga)
df.ts
```

```{r}
summary(df.ts)
```

```{r}
ts.plot(df.ts, xlab="Time Period ", ylab="harga", 
        main = "Time Series Plot")
points(df.ts)
```
# Single Moving Average

```{r}
n <- nrow(df)

n_train <- floor(0.8 * n)

training_ma <- df[1:n_train, ]
testing_ma  <- df[(n_train+1):n, ]

train_ma.ts <- ts(training_ma$Harga)
test_ma.ts  <- ts(testing_ma$Harga)
```


```{r}
plot(df.ts, col="red",main="Plot semua data")
points(df.ts)
```

```{r}
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)
```

```{r}
plot(test_ma.ts, col="blue",main="Plot data uji")
points(test_ma.ts)
```

```{r}
ggplot() + 
  geom_line(data = training_ma, aes(x = Tanggal, y = Harga, col = "Data Latih")) +
  geom_line(data = testing_ma, aes(x = Tanggal, y = Harga, col = "Data Uji")) +
  labs(x = "Periode Waktu", y = "harga", color = "Legend") +
   scale_colour_manual(name="Keterangan:", breaks = c("Data Latih", "Data Uji"),
                      values = c("blue", "red")) + 
  theme_bw() + theme(legend.position = "bottom",
                     plot.caption = element_text(hjust=0.5, size=12))
```


```{r}
data.sma<-SMA(train_ma.ts, n=3)
data.sma
```
```{r}
data.ramal<-c(NA,data.sma)
data.ramal
```

```{r}
n <- length(df.ts)   

data.gab <- cbind(
  aktual    = c(df.ts),
  pemulusan = c(data.sma, rep(NA, n - length(data.sma))),
  ramalan   = c(data.ramal, rep(tail(data.ramal,1), n - length(data.ramal)))
)

data.gab
```

```{r}
ts.plot(df.ts, xlab="Time Period ", ylab="Sales", main= "SMA N=3 Data Sales")
points(df.ts)
lines(data.gab[,2],col="green",lwd=2)
lines(data.gab[,3],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.5)
```

```{r}
error_train.sma = train_ma.ts-data.ramal[1:length(train_ma.ts)]

SSE_train.sma = sum(error_train.sma[5:length(train_ma.ts)]^2)
MSE_train.sma = mean(error_train.sma[5:length(train_ma.ts)]^2)
MAPE_train.sma = mean(abs((error_train.sma[5:length(train_ma.ts)]/train_ma.ts[5:length(train_ma.ts)])*100))

akurasi_train.sma <- matrix(c(SSE_train.sma, MSE_train.sma, MAPE_train.sma))
row.names(akurasi_train.sma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.sma) <- c("Akurasi m = 3")
akurasi_train.sma
```

```{r}
pred_test <- tail(data.ramal, length(test_ma.ts))  
error_test.sma <- test_ma.ts - pred_test

SSE_test.sma  <- sum(error_test.sma^2)
MSE_test.sma  <- mean(error_test.sma^2)
MAPE_test.sma <- mean(abs(error_test.sma / test_ma.ts * 100))

akurasi_test.sma <- matrix(c(SSE_test.sma, MSE_test.sma, MAPE_test.sma))
row.names(akurasi_test.sma) <- c("SSE","MSE","MAPE")
colnames(akurasi_test.sma) <- c("Akurasi m = 3")
akurasi_test.sma
```
# Double Moving Average 

```{r}
dma <- SMA(data.sma, n = 4)
At <- 2*data.sma - dma
Bt <- 2/(4-1)*(data.sma - dma)
data.dma<- At+Bt
data.ramal2<- c(NA, data.dma)

t = 1:24
f = c()

for (i in t) {
  f[i] = At[length(At)] + Bt[length(Bt)]*(i)
}

data.gab2 <- cbind(aktual = c(df.ts), 
                   pemulusan1 = c(data.sma,rep(NA,24)),
                   pemulusan2 = c(dma, rep(NA,24)),
                   At = c(At, rep(NA,24)), 
                   Bt = c(Bt,rep(NA,24)),
                   ramalan = c(data.ramal2, f[-1]))
data.gab2
```
```{r}
ts.plot(df.ts, xlab="Time Period ", ylab="Sales", main= "DMA N=4 Data Sales")
points(df.ts)
lines(data.gab2[,3],col="green",lwd=2)
lines(data.gab2[,6],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.8)
```

```{r}
error_train.dma = train_ma.ts-data.ramal2[1:length(train_ma.ts)]

SSE_train.dma = sum(error_train.dma[8:length(train_ma.ts)]^2)
MSE_train.dma = mean(error_train.dma[8:length(train_ma.ts)]^2)
MAPE_train.dma = mean(abs((error_train.dma[8:length(train_ma.ts)]/train_ma.ts[8:length(train_ma.ts)])*100))

akurasi_train.dma <- matrix(c(SSE_train.dma, MSE_train.dma, MAPE_train.dma))
row.names(akurasi_train.dma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.dma) <- c("Akurasi m = 4")
akurasi_train.dma
```

```{r}
error_test.dma = test_ma.ts-data.gab2[97:120,6]
SSE_test.dma = sum(error_test.dma^2)
MSE_test.dma = mean(error_test.dma^2)
MAPE_test.dma = mean(abs((error_test.dma/test_ma.ts*100)))

akurasi_test.dma <- matrix(c(SSE_test.dma, MSE_test.dma, MAPE_test.dma))
row.names(akurasi_test.dma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.dma) <- c("Akurasi m = 4")
akurasi_test.dma
```

#




